---
server:
    port: 8081
spring:
    application:
      name: account
    config:
      import: optional:configserver:http://configserver:8070
management:
  endpoint:
    shutdown:
      enabled: true
  auditevents:
    enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

eureka :
  instance:
    appname: account
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8090/eureka/

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
    instances:
      detailsForCustomerSupportApp:
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 2
        waitDurationInOpenState: 30000
  ratelimiter:
    configs:
      default:
        registerHealthIndicator: true
    instances:
      sayHello:
        limitForPeriod: 1
        limitRefreshPeriod: 5000
        timeoutDuration: 5000
      rateLimiterForCustomerDetails:
        limitForPeriod: 1
        limitRefreshPeriod: 5000
        timeoutDuration: 5000
  retry:
    configs:
      default:
        registerHealthIndicator: true
    instances:
      retryForCustomerDetails:
        maxRetryAttempts: 3
        waitDuration: 2000