---
spring:
    application:
      name: account
    config:
      import: optional:configserver:http://localhost:8070/
    security:
      oauth2:
        resourceserver:
          jwt:
            jwk-set-uri: http://localhost:8080/realms/master/protocol/openid-connect/certs
            #issuer-uri: http://localhost:9000
logging:
  level:
    org:
      springframework:
        security: TRACE