---
server:
    port: 8081
spring:
    application:
      name: account
    config:
      import: optional:configserver:http://configserver:8070
management:
  endpoint:
    shutdown:
      enabled: true
  auditevents:
    enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

eureka :
  instance:
    appname: account
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8090/eureka/

